// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OpNoteApi.Data;

#nullable disable

namespace OpNoteApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("OpNoteApi.Models.OpNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("An")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.PrimitiveCollection<string>("Anesthesiologist")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.PrimitiveCollection<string>("Assist")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("BloodLoss")
                        .HasColumnType("int");

                    b.PrimitiveCollection<string>("CirculateNurse")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time(0)");

                    b.Property<string>("Hn")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.PrimitiveCollection<string>("NurseAnesthetis")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateOnly>("OpDate")
                        .HasColumnType("date");

                    b.Property<string>("OpFinding")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Patho")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PostopDx")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PreopDx")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Procedure")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.PrimitiveCollection<string>("ScrubNurse")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time(0)");

                    b.PrimitiveCollection<string>("Surgeons")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("OpNotes");
                });

            modelBuilder.Entity("OpNoteApi.Models.OpPicture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("An")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte[]>("Content")
                        .HasColumnType("longblob");

                    b.Property<string>("Hn")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OpType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("OpPictures");
                });

            modelBuilder.Entity("OpNoteApi.Models.OpTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DoctorCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Procedure")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("OpTemplates");
                });
#pragma warning restore 612, 618
        }
    }
}
